AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    ProjectName:
        Type: String
        Description: "Name of Project"
Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${ProjectName}-group5-attendunce-bucket'
      # AccessControl: PublicRead

