name: Deploy Frontend with CloudFormation

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Frontend of Attendunce v0.1'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file .github/workflows/stacks/testStackCF.yml \
          --stack-name ${{ github.event.inputs.project_name }}-stack \
          --parameter-overrides ProjectName=${{ github.event.inputs.project_name }} \
          --capabilities CAPABILITY_IAM
    - name: Deploy frontend to S3
      run: aws s3 sync ./dist/ ${{ secrets.S3_BUCKET }} --delete
